[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tcanicula-kernel/src/arch/riscv64/linker.ld",
    "-Cforce-frame-pointers=yes",
]
