[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[target.x86_64-unknown-none]
rustflags = [
    "-Clink-arg=-Tcanicula-kernel/src/linker/x86-linker.ld",
]

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tcanicula-kernel/src/linker/riscv64-linker.ld",
    "-Cforce-frame-pointers=yes",
]
